apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opensearch

resources:
  - namespace.yaml
  - secret.yaml
  - service.yaml
  - opensearch-securityconfig-secret.yaml

helmCharts:
  - name: opensearch-operator
    includeCRDs: true
    releaseName: opensearch-operator
    version: 2.7.0
    repo: https://opensearch-project.github.io/opensearch-k8s-operator/
    valuesInline:
      installCRDs: true
  - name: opensearch-cluster
    includeCRDs: true
    releaseName: opensearch-cluster
    version: 3.0.0
    repo: https://opensearch-project.github.io/opensearch-k8s-operator/
    valuesFile: opensearch-cluster-values.yaml

patches:
  - path: opensearch-cluster-patch.yaml
