apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-wide-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/melanmeg/my-k8s-app
        revision: main
        directories:
          - path: k8s-manifests/cluster-wide-apps/*
  template:
    metadata:
      # 各Application が argocd namespace に配置されるため prefix した方が安全
      name: "cluster-wide-apps-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: cluster-wide-apps
      source:
        repoURL: https://github.com/melanmeg/my-k8s-app
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "cluster-wide-apps"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
# See the following file for documentations
# https://github.com/argoproj/argo-cd/blob/a6c664b2aefc513936e9f56c1a373bdbddcd5727/docs/operator-manual/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-wide-app-resources
  namespace: argocd
spec:
  project: argocd-root
  source:
    repoURL: https://github.com/melanmeg/my-k8s-app
    targetRevision: main
    path: k8s-manifests/cluster-wide-app-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: "cluster-wide-apps"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-resources
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/melanmeg/my-k8s-app
        revision: main
        directories:
          - path: k8s-manifests/argocd/overlays
  template:
    metadata:
      name: "{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: argocd-resources
      source:
        repoURL: https://github.com/melanmeg/my-k8s-app
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: twicas-monitoring-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/melanmeg/my-k8s-app
        revision: main
        directories:
          - path: k8s-manifests/apps/twicas-monitoring
  template:
    metadata:
      name: "{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: twicas-monitoring
      source:
        repoURL: https://github.com/melanmeg/my-k8s-app
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: twicas-monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
          - Replace=true
        retry:
          limit: -1
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 2m
