apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-client
spec:
  containers:
    - name: rabbitmq-client
      image: artshmelev/rabbitmq-pika:latest
      command: ["python", "/scripts/create_channel.py"]
      volumeMounts:
        - name: script-volume
          mountPath: /scripts
  volumes:
    - name: script-volume
      configMap:
        name: rabbitmq-client-scripts
