# ref: https://qiita.com/arila/items/3c453b7e802639eebdea
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: misskey-config
data:
  default.yml: |
    url: https://test-pekoraskey.melanmeg.com/
    port: 3000
    db:
      host: postgres.misskey
      port: 5432
      db: misskey
      user: misskey-user
    dbReplications: false
    redis:
      host: redis.misskey
      port: 6379
    meilisearch:
      host: meilisearch.misskey
      port: 7700
      apiKey: 'Yl5NDX7ft63MDoSqTsseHxNcToFpTGOC'
      ssl: false
      index: 'test-pekoraskey.melanmeg.com'
    id: 'aidx'
    proxyBypassHosts:
      - api.deepl.com
      - api-free.deepl.com
      - www.recaptcha.net
      - hcaptcha.com
      - challenges.cloudflare.com
    proxyRemoteFiles: true
    signToActivityPubGet: true
---
apiVersion: v1
kind: Service
metadata:
  name: misskey-service
  labels:
    app: misskey
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: misskey
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: misskey-files
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: my-longhorn-sc
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: misskey-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: misskey
  template:
    metadata:
      labels:
        app: misskey
    spec:
      containers:
        - name: misskey
          image: misskey/misskey:2023.12.0
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          ports:
            - name: web
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: misskey-files
              mountPath: /misskey/files
            - name: misskey-config
              mountPath: /misskey/.config
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2048Mi
          readinessProbe:
            httpGet:
              path: /
              port: 3000
      volumes:
        - name: misskey-files
          persistentVolumeClaim:
            claimName: misskey-files
        - name: misskey-config
          configMap:
            name: misskey-config
            items:
              - key: default.yml
                path: default.yml
