apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30052
      protocol: TCP
  selector:
    application: spilo
    cluster-name: postgres-cluster
    spilo-role: replica

---
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: postgres-cluster
  labels:
    app: postgres-zalando
    kind: postgres-cluster
spec:
  env:
    - name: POSTGRES_DB
      value: misskey
    - name: POSTGRES_USER
      value: misskey-user
    - name: POSTGRES_PASSWORD
      value: misskey-pass
  teamId: "acid"
  volume:
    size: 8Gi
  numberOfInstances: 2
  users:
    zalando: # database owner
      - superuser
      - createdb
    misskey-user: # database owner
      - superuser
      - createdb
    foo_user: [] # role for application foo
  databases:
    foo: zalando # dbname: owner
    misskey: misskey-user # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
