# ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Application reconciliation timeout is the max amount of time required to discover if a new manifests version got
  # published to the repository. Reconciliation by timeout is disabled if timeout is set to 0. Three minutes by default.
  # > Note: argocd-repo-server deployment must be manually restarted after changing the setting.
  timeout.reconciliation: 30s
  # With a large number of applications, the periodic refresh for each application can cause a spike in the refresh queue
  # and can cause a spike in the repo-server component. To avoid this, you can set a jitter to the sync timeout, which will
  # spread out the refreshes and give time to the repo-server to catch up. The jitter is the maximum duration that can be
  # added to the sync timeout. So, if the sync timeout is 3 minutes and the jitter is 1 minute, then the actual timeout will
  # be between 3 and 4 minutes. Disabled when the value is 0, defaults to 0.
  timeout.reconciliation.jitter: 15s
  admin.enabled: "false"
  resource.exclusions: |
    - apiGroups:
      - cilium.io
      kinds:
      - CiliumIdentity
      clusters:
      - "*"
