global:
  storageClass: "my-longhorn-sc"

kubeVersion: "1.30.4"

image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.9.0-debian-12-r4
  pullPolicy: IfNotPresent

listeners:
  client:
    containerPort: 9092
    protocol: SASL_PLAINTEXT
    name: CLIENT
  controller:
    name: CONTROLLER
    containerPort: 9093
    protocol: SASL_PLAINTEXT
  interbroker:
    containerPort: 9094
    protocol: SASL_PLAINTEXT
    name: INTERNAL
  external:
    containerPort: 9095
    protocol: SASL_PLAINTEXT
    name: EXTERNAL

sasl:
  enabledMechanisms: PLAIN,SCRAM-SHA-256,SCRAM-SHA-512
  interBrokerMechanism: PLAIN
  controllerMechanism: PLAIN
  interbroker:
    user: inter_broker_user
    password: "testPassword123" # 仮のパスワード
    clientId: inter_broker_client
    clientSecret: "testSecret123" # 仮のクライアントシークレット
  controller:
    user: controller_user
    password: "testPassword123" # 仮のパスワード
    clientId: controller_broker_client
    clientSecret: "testSecret123" # 仮のクライアントシークレット
  client:
    users:
      - user1
    passwords: "testPassword123" # 仮のパスワード
  zookeeper:
    user: "zookeeper_user"
    password: "testPassword123" # 仮のパスワード
  existingSecret: ""

controller:
  replicaCount: 3
  controllerOnly: false
  minId: 0
  zookeeperMigrationMode: false

broker:
  replicaCount: 3
  minId: 100
  zookeeperMigrationMode: false

kraft:
  enabled: false

zookeeper:
  enabled: true
