apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opensearch

resources:
  - namespace.yaml
  - opensearch-operator.yaml
  - secret.yaml
  - service.yaml
  # - opensearch-cluster.yaml
