---
# Source: opensearch-cluster/templates/opensearch-cluster-cr.yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: default
spec:
  initHelper:
    imagePullPolicy: IfNotPresent
  general:
    version: 2.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: opensearch-cluster
    setVMMaxMapCount: true
    drainDataNodes: true
  dashboards:
    version: 2.3.0
    enable: true
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 500m
      roles:
        - master
        - data
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true
    config:
      adminCredentialsSecret:
        name: opensearch-secret
  internal_users.yml: |-
    _meta:
      type: "internalusers"
      config_version: 2
    admin:
      # htpasswd -nbBC 10 "" your_password | tr -d ':\n' | sed 's/$2y/$2a/'
      hash: "$2a$10$uan2XQLnY1QCt80LeOb.9OkZudbP6wY6/lKSGROs9Tx0LZj8infXe"   <------- change that hash to your new password hash
      reserved: true
      backend_roles:
      - "admin"
      description: "Demo admin user"
