# ref: https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/opensearch-operator/examples/2.x/opensearch-cluster-custom-admin-user.yaml
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
spec:
  general:
    version: 2.14.0
    httpPort: 9200
    vendor: opensearch
    serviceName: my-cluster
  security:
    config:
      adminCredentialsSecret:
        name: opensearch-secret
      securityConfigSecret:
        name: opensearch-securityconfig-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
  dashboards:
    opensearchCredentialsSecret:
      name: opensearch-secret
    version: 2.14.0
    enable: true
    replicas: 2
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      nodeSelector:
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
