apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: admin
  namespace: default
spec:
  opensearchCluster:
    name: opensearch-cluster
  passwordFrom:
    name: opensearch-secret
    key: password
  backendRoles:
    - master
    - data
