apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
spec:
  security:
    config:
      adminCredentialsSecret:
        name: opensearch-secret
      securityConfigSecret:
        name: opensearch-securityconfig-secret
