apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: grafana
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30042
      protocol: TCP
  selector:
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/name: grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 8.5.0
    helm:
      releaseName: grafana
      values: |
        adminUser: grafana
        adminPassword: grafana
        replicas: 2

        serviceMonitor:
          enabled: true
          labels:
            release: prometheus

        persistence:
          type: pvc
          enabled: true
          accessModes:
            - ReadWriteOnce
          size: 10Gi
          finalizers:
            - kubernetes.io/pvc-protection
          inMemory:
            enabled: true

        resource:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi

        datasources:
          datasources1.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              uid: Prometheus
              access: proxy
              orgId: 1
              url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
              basicAuth: false
              version: 1
              editable: false
              jsonData:
                httpMethod: POST
                manageAlerts: true
                prometheusType: Prometheus

          datasources2.yaml:
            apiVersion: 1
            datasources:
            - name: Loki
              type: loki
              uid: Loki
              access: proxy
              orgId: 1
              url: http://loki-gateway.logging
              basicAuth: false
              version: 1
              editable: false
              jsonData:
                maxLines: 1000
                derivedFields:
                  - datasourceUid: 'Tempo'
                    matcherRegex: '"request_X-B3-Traceid":"(\w+)"'
                    name: TraceID
                    url: $${__value.raw}

          datasources3.yaml:
            apiVersion: 1
            datasources:
            - name: Tempo
              type: tempo
              uid: Tempo
              access: proxy
              orgId: 1
              url: http://tempo-distributed-query-frontend.tracing:3100
              basicAuth: false
              version: 1
              editable: false
              jsonData:
                httpMethod: GET
                tracesToLogs:
                  datasourceUid: 'Loki'
                  tags: ['job', 'instance', 'pod', 'namespace']
                  mappedTags: [{ key: 'service.name', value: 'service' }]
                  mapTagNamesEnabled: false
                  spanStartTimeShift: '1h'
                  spanEndTimeShift: '1h'
                  filterByTraceID: false
                  filterBySpanID: false
                tracesToMetrics:
                  datasourceUid: 'Prometheus'
                  tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
                  queries:
                    - name: 'Sample query'
                      query: 'sum(rate(traces_spanmetrics_latency_bucket{$__tags}[5m]))'
                serviceMap:
                  datasourceUid: 'Prometheus'
                search:
                  hide: false
                nodeGraph:
                  enabled: true
                lokiSearch:
                  datasourceUid: 'Loki'

          datasources4.yaml:
           apiVersion: 1
           datasources:
           - name: Pyroscope
             type: grafana-pyroscope-datasource
             uid: Pyroscope
             url: http://pyroscope-querier.pyroscope:4040

        dashboards:
          default:
            prometheus-stats:
              gnetId: 2
              revision: 2
              datasource: Prometheus
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
