apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboard-lb
  namespace: opensearch
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30085
      protocol: TCP
  selector:
    opensearch.cluster.dashboards: opensearch-cluster-1
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-lb
  namespace: opensearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30086
      protocol: TCP
  selector:
    opster.io/opensearch-cluster: opensearch-cluster-1
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster-1
  namespace: opensearch
spec:
  general:
    httpPort: 9200
    serviceName: opensearch-cluster-1
    version: 2.3.0
  dashboards:
    version: 2.3.0
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "60Gi"
      resources:
        requests:
          memory: "4Gi"
          cpu: "1000m"
        limits:
          memory: "4Gi"
          cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        pvc:
          accessModes:
            - ReadWriteOnce
          storageClass: "nfs-share"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operaotr
  namespace: opensearch
spec:
  project: cluster-wide-apps
  source:
    chart: opensearch-operaotr
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator
    targetRevision: 2.6.1
    helm:
      releaseName: opensearch-operaotr
      values: |
        securityContext:
          runAsNonRoot: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
