apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: example-scaledjob
spec:
  jobTargetRef:
    parallelism: 3 # 同時に実行するジョブの数
    completions: 5 # 完了すべきジョブの総数
    backoffLimit: 2
    template:
      spec:
        containers:
          - name: example-job-container
  envSourceContainerName: example-job-container
  pollingInterval: 5
  minReplicaCount: 0
  maxReplicaCount: 100
  successfulJobsHistoryLimit: 3 # 成功したジョブの履歴を3つ保持
  failedJobsHistoryLimit: 3 # 失敗したジョブの履歴を3つ保持
  scalingStrategy:
    strategy: accurate
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://admin:admin@rabbitmq-cluster.rabbitmq:5672/
        protocol: auto
        mode: QueueLength # キュー内のメッセージ数でスケーリング
        value: "1" # キューに1メッセージが追加されるごとに Pod を1つ増加させる
        activationValue: "1" # 初期のアクティベーション値
        queueName: my_queue
        vhostName: /
        unsafeSsl: "true"
