apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: example-job-container
          image: busybox # 実行するコンテナのイメージ
          command: ["/bin/sh", "-c", "echo 'Processing job...' && sleep 30"] # ジョブの実行内容
      restartPolicy: Never
