apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher-container
          image: node:20
          ports:
            - containerPort: 3000
          command: ["sh", "-c"]
          args:
            [
              'trap ''exit 0'' SIGTERM; require() { node -e "$1"; }; require "require(''http'').createServer((req, res) => res.end(''Hello, Kubernetes!'')).listen(3000);" &; sleep 10; kill -s SIGTERM $!; wait',
            ]
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
