apiVersion: apps/v1
kind: Deployment
metadata:
  name: twicas-publisher
  labels:
    app: twicas-publisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: twicas-publisher
  template:
    metadata:
      labels:
        app: twicas-publisher
    spec:
      containers:
        - name: twicas-publisher-container
          image: melanmeg/twicas-publisher:latest
          command: ["node", "/app/dist/main.js"]
          env:
            - name: RABBITMQ_URL
              value: "https://rabbitmq-cluster.rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: admin
            - name: RABBITMQ_PASSWORD
              value: admin
            - name: PORT_NUM
              value: "18080"
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
