apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 3
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
        - name: publisher-container
          image: node:20
          ports:
            - containerPort: 3000
          command: ["node"]
          args:
            [
              "-e",
              "require('http').createServer((_, res) => res.end('Hello!')).listen(3000)",
            ]
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
            requests:
              memory: "128Mi"
              cpu: "100m"
