apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: twicas-monitoring-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: twicas-monitoring
  pollingInterval: 10 # ポーリング間隔
  cooldownPeriod: 120 # スケーリング後のクールダウン期間
  idleReplicaCount: 0 # アイドル時のレプリカ数
  minReplicaCount: 0 # 最小レプリカ数
  maxReplicaCount: 100 # 最大レプリカ数
  fallback:
    failureThreshold: 3
    replicas: 3
  advanced:
    horizontalPodAutoscalerConfig:
      name: keda-hpa-twicas-monitoring-scaler
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 120 # スケールダウンの安定化ウィンドウ
          policies:
            - type: Percent
              value: 100
              periodSeconds: 15
  triggers:
    - type: rabbitmq
      metadata:
        host: amqp://admin:admin@rabbitmq-cluster.rabbitmq:5672/
        protocol: auto
        mode: QueueLength # キュー内のメッセージ数でスケーリング
        value: "1" # キューに1メッセージが追加されるごとに Pod を1つ増加させる
        activationValue: "1" # 初期のアクティベーション値
        queueName: my_queue
        vhostName: /
        unsafeSsl: "true"
