apiVersion: v1
kind: Service
metadata:
  name: twicas-monitoring-service
  labels:
    app: twicas-monitoring
spec:
  type: ClusterIP
  ports:
    - name: app
      port: 18080
      targetPort: 18080
      protocol: TCP
  selector:
    app: twicas-monitoring
---
apiVersion: v1
kind: Service
metadata:
  name: twicas-publisher-service
  labels:
    app: twicas-publisher
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 18080
      targetPort: 18080
  selector:
    app: twicas-publisher
