apiVersion: v1
kind: Service
metadata:
  name: twicas-monitoring-service
  namespace: twicas-monitoring
  labels:
    app: twicas-monitoring
spec:
  type: NodePort
  ports:
    - name: app
      port: 18080
      targetPort: 18080
      nodePort: 30011
      protocol: TCP
  selector:
    app: twicas-monitoring
