apiVersion: apps/v1
kind: Deployment
metadata:
  name: twicas-monitoring
  labels:
    app: twicas-monitoring
spec:
  selector:
    matchLabels:
      app: twicas-monitoring
  template:
    metadata:
      labels:
        app: twicas-monitoring
    spec:
      terminationGracePeriodSeconds: 15000 # 4 hours and 10 minutes
      containers:
        - name: twicas-monitoring-container
          image: melanmeg/twicas-monitoring:1.0.0
          command: ["node", "run", "start"]
          workingDir: /app
          env:
            - name: OPENSEARCH_URL
              value: "https://my-cluster.opensearch:9200"
            - name: OPENSEARCH_USER
              value: admin
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensearch-secret
                  key: password
            - name: USER_AGENT
              value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
            - name: DOWNLOAD_DIR
              value: "downloads"
            - name: PORT_NUM
              value: "18080"
            - name: LOG_DIR
              value: "/tmp/logs"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 2Gi
