# ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.melanmeg.com
  dex.config: |
    connectors:
      - type: github
        id: github
        name: gitHub
        config:
          clientID: $dex.github.clientId
          clientSecret: $dex.github.clientSecret
          scopes:
          - openid
          - profile
          - email
          - groups
