# ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-rbac-cm-yaml/
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: "role:admin"
  scopes: "[openid, profile, groups, email]"
  policy.csv: |
    g, naoya05280708@gmail.com, role:readonly
