apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ./namespace.yaml
  - ../base
  - ./argocd-lb.yaml
  - ./argocd-secret.yaml

patches:
  - path: ./argocd-cm.yaml
  - path: ./argocd-rbac-cm.yaml
  # - path: ./node-affinity-patch/argocd-redis-ha-haproxy.yaml
