apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-store
  namespace: external-secrets
spec:
  provider:
    onepassword:
      token: "your-1password-token"
      url: "https://your-1password-url"
