apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-gcp-sm
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: my-project-melanmeg
      auth:
        workloadIdentity:
          clusterLocation: asia-northeast1
          clusterName: kubernetes
          clusterProjectID: my-project-melanmeg
          serviceAccountRef:
            name: external-secrets-sa
            namespace: external-secrets
