apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword
  namespace: onepassword
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect
      vaults:
        k8s: 1 # look in this vault first
      auth:
        secretRef:
        connectTokenSecretRef:
          name: onepassword-connect-token
          key: token
          namespace: onepassword
