# ref: `kubectl get deploy -n argocd argocd-redis-ha-haproxy -o yaml`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis-ha-haproxy
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-redis-ha-haproxy
  template:
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - env:
            - name: AUTH
              valueFrom:
                secretKeyRef:
                  key: auth
                  name: argocd-redis
          name: haproxy
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
