# ref: `kubectl get deploy -n argocd argocd-redis-ha-haproxy -o yaml`
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis-ha-haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-redis-ha-haproxy
  template:
    spec:
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - env:
            - name: AUTH
              valueFrom:
                secretKeyRef:
                  key: auth
                  name: argocd-redis
          name: haproxy
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
status:
  availableReplicas: 1
  observedGeneration: 2
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
