apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq-cluster
spec:
  replicas: 3
  secretBackend:
    externalSecret:
      name: "rabbitmq-cluster-deployment-default-user"
