apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-lb
  namespace: rabbitmq
spec:
  type: NodePort
  ports:
    - port: 15672
      targetPort: 15672
      nodePort: 30012
      protocol: TCP
  selector:
    app.kubernetes.io/name: rabbitmq-cluster
