apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-nginx
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-nginx
  template:
    metadata:
      labels:
        app: grafana-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: grafana-nginx-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-nginx-config
  namespace: grafana
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://grafana.grafana/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-nginx
  namespace: grafana
spec:
  selector:
    app: grafana-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
