apiVersion: v1
kind: Service
metadata:
  name: argocd-lb
  namespace: argocd
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: server
      nodePort: 30003
      protocol: TCP
  selector:
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-server
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: argocd-secret
  namespace: argocd
spec:
  itemPath: "vaults/my-vault/items/argocd"
