apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io/
    targetRevision: 0.10.4
    helm:
      releaseName: external-secrets
      values: |
        replicaCount: 1
        installCRDs: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
