apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: kedacore
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.16.1
    helm:
      releaseName: keda
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
