apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: 2.14.3
    helm:
      releaseName: keda
      values: |
        clusterName: kubernetes-default
        clusterDomain: cluster.local

        operator:
          name: keda-operator
          revisionHistoryLimit: 10
          replicaCount: 1
          disableCompression: true

        metricsServer:
          revisionHistoryLimit: 10
          replicaCount: 1
          disableCompression: true
          dnsPolicy: ClusterFirst
          useHostNetwork: false

        webhooks:
          enabled: true
          port: ""
          healthProbePort: 8081
          useHostNetwork: false
          name: keda-admission-webhooks
          revisionHistoryLimit: 10
          replicaCount: 1
          failurePolicy: Ignore

        rbac:
          create: true
          aggregateToDefaultRoles: false
          enabledCustomScaledRefKinds: true
          controlPlaneServiceAccountsNamespace: kube-system
          scaledRefKinds:
            - apiGroup: "*"
              kind: "*"

        serviceAccount:
          operator:
            create: true
          metricServer:
            create: true
          webhooks:
            create: true

        resources:
          operator:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          metricServer:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi
          webhooks:
            limits:
              cpu: 1
              memory: 1000Mi
            requests:
              cpu: 100m
              memory: 100Mi

        http:
          timeout: 3000
          keepAlive:
            enabled: true
          minTlsVersion: TLS12

        prometheus:
          metricServer:
            enabled: false
          operator:
            enabled: false
          webhooks:
            enabled: false

        opentelemetry:
          collector:
            uri: ""
          operator:
            enabled: false

        certificates:
          autoGenerated: true

        crds:
          additionalAnnotations:
            argocd.argoproj.io/sync-options: ServerSideApply=true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Fix scaledjobs.keda.sh CRD is too long.
