apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.7.2
    helm:
      releaseName: longhorn
      values: |
        defaultSettings:
          orphanAutoDeletion: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
