# apiVersion: v1
# kind: Service
# metadata:
#   name: minio-lb
#   namespace: tenant-1
# spec:
#   type: NodePort
#   ports:
#     - port: 9090
#       targetPort: 9090
#       nodePort: 30005
#       protocol: TCP
#   selector:
#     v1.min.io/tenant: minio-tenant-1
# ---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
spec:
  project: cluster-wide-apps
  source:
    chart: minio-operator
    repoURL: https://operator.min.io/
    targetRevision: 6.0.4
    helm:
      releaseName: minio-operator
      values:
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
