apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  project: cluster-wide-apps
  source:
    chart: opensearch-cluster
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator
    targetRevision: 2.6.1
    helm:
      releaseName: opensearch-cluster
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
