apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: opensearch-secret
  namespace: opensearch
spec:
  itemPath: "vaults/my-vault/items/opensearch"
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-lb
  namespace: opensearch
spec:
  type: NodePort
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30009
      protocol: TCP
  selector:
    opster.io/opensearch-cluster: opensearch-cluster-1
---
apiVersion: v1
kind: Service
metadata:
  name: opensearch-dashboard-lb
  namespace: opensearch
spec:
  type: NodePort
  ports:
    - port: 5601
      targetPort: 5601
      nodePort: 30010
      protocol: TCP
  selector:
    opensearch.cluster.dashboards: opensearch-cluster-1
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  project: cluster-wide-apps
  source:
    chart: opensearch-cluster
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator
    targetRevision: 2.7.0
    helm:
      releaseName: opensearch-cluster
      values: |
        cluster:
          general:
            serviceName: "opensearch-cluster-1"
          dashboards:
            enable: true
            replicas: 1
          tls:
            enable: false
          nodePools:
            - component: masters
              replicas: 3
              diskSize: "10Gi"
              roles:
                - "master"
                - "data"
              persistence:
                pvc:
                  storageClass: my-longhorn-sc
                  accessModes:
                  - ReadWriteOnce
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
                  cpu: "1000m"
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-operaotr
  namespace: opensearch
spec:
  project: cluster-wide-apps
  source:
    chart: opensearch-operaotr
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator
    targetRevision: 2.7.0
    helm:
      releaseName: opensearch-operaotr
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
