apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  project: cluster-wide-apps
  source:
    chart: opensearch-cluster
    repoURL: https://opensearch-project.github.io/opensearch-k8s-operator
    targetRevision: 2.6.1
    helm:
      releaseName: opensearch-cluster
      values: |
        cluster:
          general:
            serviceName: "opensearch-cluster"
          dashboards:
            enable: true
            replicas: 1
          tls:
            enable: false
          nodePools:
            - component: masters
              replicas: 3
              diskSize: "10Gi"
              roles:
                - "master"
                - "data"
              persistence:
                pvc:
                  storageClass: my-longhorn-sc
                  accessModes:
                    - ReadWriteOnce
              resources:
                requests:
                  memory: "2Gi"
                  cpu: "500m"
                limits:
                  memory: "4Gi"
                  cpu: "1000m"
  destination:
    server: https://kubernetes.default.svc
    namespace: opensearch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
