# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: twicas-monitoring-shared-pv
# spec:
#   capacity:
#     storage: 50Gi
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: "nfs-share"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: twicas-monitoring-shared-pvc
#   namespace: twicas-monitoring
# spec:
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 50Gi
#   storageClassName: "nfs-share"
# ---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: twicas-monitoring-deployment
  namespace: twicas-monitoring
  labels:
    app: twicas-monitoring
spec:
  serviceName: "twicas-monitoring"
  replicas: 1
  selector:
    matchLabels:
      app: twicas-monitoring
  template:
    metadata:
      labels:
        app: twicas-monitoring
    spec:
      containers:
        - name: twicas-monitoring-container
          image: melanmeg/twicas-monitoring:1.0.0
          env:
            - name: OPENSEARCH_URL
              value: "https://opensearch-cluster-1.opensearch:9200"
            - name: OPENSEARCH_USER
              value: admin
            - name: OPENSEARCH_PASSWORD
              value: admin
            - name: USER_AGENT
              value: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36"
            - name: DOWNLOAD_DIR
              value: "downloads"
            - name: PORT_NUM
              value: "18080"
            - name: LOG_DIR
              value: "/tmp/logs"
          resources:
            limits:
              cpu: 1000m
              memory: 2048Mi
            requests:
              cpu: 500m
              memory: 1024Mi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: twicas-monitoring-storage
              mountPath: /data
      # volumes:
      #   - name: twicas-monitoring-storage
      #     persistentVolumeClaim:
      #       claimName: twicas-monitoring-shared-pvc
  volumeClaimTemplates:
    - metadata:
        name: twicas-monitoring-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
        storageClassName: "nfs-share"
---
apiVersion: v1
kind: Service
metadata:
  name: twicas-monitoring-service
  namespace: twicas-monitoring
  labels:
    app: twicas-monitoring
spec:
  type: NodePort
  ports:
    - name: app
      port: 18080
      targetPort: 18080
      nodePort: 30087
      protocol: TCP
  selector:
    app: twicas-monitoring
