apiVersion: v1
kind: Service
metadata:
  name: twicas-flask-service
  namespace: twicas-monitoring
  labels:
    app: twicas-flask
spec:
  type: NodePort
  ports:
    - name: app
      port: 5000
      targetPort: 5000
      nodePort: 30088
      protocol: TCP
  selector:
    app: twicas-flask
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: twicas-flask-deployment
  namespace: twicas-monitoring
  labels:
    app: twicas-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twicas-flask
  template:
    metadata:
      labels:
        app: twicas-flask
    spec:
      containers:
        - name: twicas-flask-container
          image: melanmeg/twicas-flask:1.0.0
          env:
            - name: TOKEN
              value: "dummy" # dummy
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "200m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
