apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

patches:
  - patch: |-
      - op: replace
        path: /data/default-setting.yaml
        value: |
          backup-target: nfs://192.168.11.12:/mnt/nfsshare/k8s/share
